### ISSUE TITLE
CellLine: add LINCS Project Id field

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#100]
For the CellLine resource, could the field "lincs_id" be added?

For example, for [CHEMBL3307242](https://www.ebi.ac.uk/chembl/api/data/cell_line/CHEMBL3307242.json):

```
{
  cell_chembl_id: "CHEMBL3307242",
  cell_description: "P3HR-1",
  cell_id: 2,
  cell_name: "P3HR-1",
  cell_source_organism: "Homo sapiens",
  cell_source_tax_id: 9606,
  cell_source_tissue: "Lyphoma",
  cellosaurus_id: "CVCL_2676",
  clo_id: "CLO_0008331",
  efo_id: "EFO_0002312",
  lincs_id:"LCL-2024" <---
}
```

**Comment by mnowotka** [comment]
fixed in the code and ready to deploy, the filed name will be `cl_lincs_id`.

**Comment by mnowotka** [comment]
Deployed to dev server: https://wwwdev.ebi.ac.uk/chembl/api/data/cell_line/CHEMBL3307242.json

**Comment by nclopezo** [comment]
This has been added to the cell line report card: http://glados-ebitest.rhcloud.com/cell_line_report_card/CHEMBL3307242/
