### ISSUE TITLE
Assays: Add curation summary information. 

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#101]
Can we add the curation summary for an assay? 

Like this:

```
{
  assay_category: null,
  assay_cell_type: "MDCK",
  assay_chembl_id: "CHEMBL931654",
  ...
  curation_summary: [
    {
      target:_name: "Neuraminidase",
      target_chembl_id: "SINGLE_PROTEIN",
      target_description: "<description>"
    },
    ...
  ]

}
```

**Comment by mnowotka** [comment]
weqeq
cl_lincs_id
sadasd

**Comment by mnowotka** [comment]
Since there is only one target for each assay and you can get the target_chembl_id from assay, I suggest you just do another request to the target endpoint.

**Comment by nclopezo** [comment]
For the record, this has been implemented: https://www.ebi.ac.uk/panda/jira/browse/CHEMBLWEB-11
