### ISSUE TITLE
Documents: add some properties to the resource.

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#102]
It seems that when the information of a document is requested, the author and title are always null. Also the abstract is not included in the properties.

**Comment by mnowotka** [comment]
Authors are not always null, see: https://www.ebi.ac.uk/chembl/api/data/document?authors__isnull=false
Title is not always null, see: https://www.ebi.ac.uk/chembl/api/data/document?title__isnull=false
Abstract is not included yet but it will be included in ChEMBL 22.

**Comment by mnowotka** [comment]
@nclopezo - can I close this one?

**Comment by nclopezo** [comment]
yes
