### ISSUE TITLE
Some Targets Missing?

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#105]
I am not sure if this is normal due to the current configuration, there are some targets for which I can't fetch the information. 
I was using the development server to get the target relations for [CHEMBL3559691](http://glados-ebitest.rhcloud.com/target_report_card/CHEMBL3559691/#TargetRelations) 

The development server returns 46 records, while the [production server](https://www.ebi.ac.uk/chembl/target/inspect/CHEMBL3559691) returns 44.

After getting the list of target relations from development server, I get some additional information required for each target like [this](https://wwwdev.ebi.ac.uk/chembl/api/data/target.json?target_chembl_id__in=CHEMBL1795191,CHEMBL1795192,CHEMBL1907600,CHEMBL1907601,CHEMBL1907602,CHEMBL1907605,CHEMBL2094126,CHEMBL2094127,CHEMBL2094128,CHEMBL2095942,CHEMBL2111288,CHEMBL2111326,CHEMBL2111389,CHEMBL2111444,CHEMBL2111448,CHEMBL2111455,CHEMBL2508,CHEMBL301,CHEMBL3038467,CHEMBL3038468,CHEMBL3038469,CHEMBL3038470,CHEMBL3038471,CHEMBL3038472,CHEMBL3038473,CHEMBL3038474,CHEMBL3038475,CHEMBL3038517,CHEMBL3055,CHEMBL308,CHEMBL3116,CHEMBL3301385,CHEMBL3301386,CHEMBL331,CHEMBL3559690,CHEMBL3559692,CHEMBL4036,CHEMBL4442,CHEMBL4597,CHEMBL5316,CHEMBL5719,CHEMBL5790,CHEMBL5808,CHEMBL5856,CHEMBL6002,CHEMBL6162&order_by=target_chembl_id&limit=1000). 

But CHEMBL4036 and CHEMBL3559690 are not in the response of the development server, shouldn't these 2 be in the response from the development server?

**Comment by agaulton** [comment]
Which database/schema is development server pointing at currently?

**Comment by nclopezo** [comment]
The web services should be pointing at the current chembl22, the web interface is pointing at chembl21.

**Comment by nclopezo** [comment]
I mean, the web interface in the development server is using chembl21 https://wwwdev.ebi.ac.uk/chembl/

**Comment by agaulton** [comment]
Ok so if http://glados-ebitest.rhcloud.com/target_report_card/CHEMBL3559691/#TargetRelations is pointing at the chembl schema on chempro(?) that explains the difference. In the main schema two of the targets are downgraded (target_dictionary.downgraded = 1). In the release schemas (chembl_21/chembl_21_app etc) I remove downgraded data, so you don't see these targets at all.

**Comment by nclopezo** [comment]
I will also discuss it with Michal, but for the record, for this one it seems that none of the targets are available: http://glados-ebitest.rhcloud.com/target_report_card/CHEMBL2363965/#TargetRelations
