### ISSUE TITLE
Add some compound properties

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#106]
The [molecules_properties](https://www.ebi.ac.uk/chembl/api/data/molecule.json?molecule_chembl_id=CHEMBL25) part of a molecule is being used to render the [Calculated Compound Parent Properties](http://glados-ebitest.rhcloud.com/compound_report_card/CHEMBL25/#CalculatedCompoundParentProperties) section of the report card. 

However, I don't see these properties in the response:
- HBA Lipinski
- HBD Lipinski
- Ro5 Violations (Lipinski)

Could these be added? Or these can be calculated from the current response in some way?

**Comment by nclopezo** [comment]
These properties are shown in the current interface: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL25

**Comment by mnowotka** [comment]
Done!
