### ISSUE TITLE
Molecule: molecule indications

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#107]
In the current interface there is a section called "[Indications](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL25/#indications_CHEMBL25_wrapper)" How can this information be obtained using the current web services? Or could they be added to the response?

**Comment by mnowotka** [comment]
Question to @agaulton - is drug_indications_mv used in the compound report card? If not then, where? Also, where is the code that creates MV? Is that a part of the UI or some preprocessing step done during the release?

**Comment by mnowotka** [comment]
There is a drug indication endpoint - please have a look: http://localhost:8000/chembl_webservices/chembl_ws/drug_indication.json but you will probably have to ask @agaulton how to combine it with information about molecule hierarchy to get data presented as expected.
