### ISSUE TITLE
Molecule: Structural Alerts

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#109]
In the current interface, in the compound report card there is the section [Structural Alerts](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL25). How can this information be obtained using the current web services? Or could it be added to the response?

**Comment by mnowotka** [comment]
Done, examples:

- https://www.ebi.ac.uk/chembl/api/data/compound_structural_alert.json?molecule_chembl_id=CHEMBL266429
- https://www.ebi.ac.uk/chembl/api/data/compound_structural_alert/898.png
