### ISSUE TITLE
Molecule: Target Predictions

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#110]
In the current interface, in the compound report card there is the section [Target Predictions](https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL25). How can this information be obtained using the current web services? Or could it be added to the response?

**Comment by mnowotka** [comment]
Done, example:

https://www.ebi.ac.uk/chembl/api/data/document_similarity.json?document_1_chembl_id=CHEMBL1122254

**Comment by mnowotka** [comment]
Sorry, not yet done :P

**Comment by mnowotka** [comment]
This endpoint is now deployed: https://www.ebi.ac.uk/chembl/api/data/target_prediction.json
So for example all target predictions for Aspirin:
https://www.ebi.ac.uk/chembl/api/data/target_prediction.json?molecule_chembl_id=CHEMBL25
All molecules for which target CHEMBL2026 was predicted:
https://www.ebi.ac.uk/chembl/api/data/target_prediction.json?target_chembl_id=CHEMBL2026
