### ISSUE TITLE
Document: add related documents. 

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#111]
Could the related documents can be added to the document end point?
For example:

For
https://wwwdev.ebi.ac.uk/chembl/api/data/document.json?document_chembl_id=CHEMBL1121978

```
{
...
title: "Ultra-short-acting beta-adrenergic receptor blocking agents. 2. (Aryloxy)propanolamines containing esters on the aryl function.",
volume: "25",
year: 1982, 
related_documents: ["CHEMBL3272119", "CHEMBL3244030", "CHEMBL3244015", "CHEMBL3227933", "CHEMBL1123848"]
}
```

**Comment by mnowotka** [comment]
Done, example:

https://www.ebi.ac.uk/chembl/api/data/document_similarity.json?document_1_chembl_id=CHEMBL1122254
