### ISSUE TITLE
taxonomy ID for targtes

### ISSUE THREAD

**Issue by piotr-gawron** [chembl/chembl_webservices_2#132]
It would be great to have taxonomy ID apart from string organism name in the chembl responses.

Here is an example:

https://www.ebi.ac.uk/chembl/api/data/target?limit=1000&target_components__accession=O60391

organism is marked as "Homo sapiens". From my point of view it would be much easier if it refered to taxonomy ID: [9606](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9606).

**Comment by mnowotka** [comment]
Yes I agree, this will be done in the next minor release.

**Comment by mnowotka** [comment]
This is now implemented.
