### ISSUE TITLE
next page url is not correct

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_webservices_2#133]
the substructure endpoint is not generating the next page url in the way the same way other endpoints do:

https://www.ebi.ac.uk/chembl/api/data/substructure/CHEMBL59.json?size=2

It replies:

`next: ".json?chembl_id=CHEMBL59&offset=20&limit=20&size=2",`

It is missing the path **/chembl/api/data/substructure**

**Comment by mnowotka** [comment]
Fixed.
