### ISSUE TITLE
Add SRC_ID to Document Endpoint

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#140]
Wee need it in order to finish https://github.com/chembl/GLaDOS/issues/291

**Comment by mnowotka** [comment]
In chembl_app schema, DOCS table doesn't have FK to SOURCE so I can't add it.
@agaulton and @eloyfelix - please have a look.

**Comment by agaulton** [comment]
src_id will be added to docs table from chembl_24 onwards (see chembl schema), but can leave for now...

**Comment by juanfmx2** [comment]
this has just been deployed:
https://www.ebi.ac.uk/chembl/api/data/document.json
