### ISSUE TITLE
Support CHEMBL_ID search for flexmatch

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_webservices_2#141]
It would be useful to be able to provide a CHEMBL ID as a parameter of a flexmatch search

Currently, it accepts smiles only:
https://www.ebi.ac.uk/chembl/api/data/molecule.json?molecule_structures__canonical_smiles__flexmatch=C

While substructure and similarity accept both.

**Comment by mnowotka** [comment]
@juanfmx2 this is now implemented: https://www.ebi.ac.uk/chembl/api/data/molecule.json?molecule_structures__canonical_smiles__flexmatch=CHEMBL25
