### ISSUE TITLE
Add compound cross references to molecule endpoint.

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#143]
This is needed to create the Compound Cross References of the compound report card:
For example: https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL25

**Comment by mnowotka** [comment]
The "cross_references" field is now added to the molecule endpoint, example: https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL25.json. The same is added to targets: https://www.ebi.ac.uk/chembl/api/data/target.json
