### ISSUE TITLE
Include short data validity comment in activity endpoint

### ISSUE THREAD

**Issue by juanfmx2** [chembl/chembl_webservices_2#147]
Using the DATA_VALIDITY_LOOKUP table:

`select concat(concat(concat(concat('"',d.DESCRIPTION ),'": "'), d.DATA_VALIDITY_COMMENT), '",') from DATA_VALIDITY_LOOKUP d;`

**Comment by mnowotka** [comment]
This is now implemented for example: https://www.ebi.ac.uk/chembl/api/data/activity/32190.json. Field name is "activity_comment".

**Comment by juanfmx2** [comment]
activity comment and data validity comment are different, the long version of the comment is already present in the activity table.
`select distinct(act.DATA_VALIDITY_COMMENT) from activities act where act.DATA_VALIDITY_COMMENT IS NOT NULL`

but the short form needs to be gathered from DATA_VALIDITY_LOOKUP table

`select d.DESCRIPTION, d.DATA_VALIDITY_COMMENT from DATA_VALIDITY_LOOKUP d;`
<img width="1016" alt="screen shot 2018-02-06 at 14 34 53" src="https://user-images.githubusercontent.com/6558395/35864883-ee6be83c-0b4a-11e8-85e0-827c9a76614a.png">

**Comment by mnowotka** [comment]
Can you please check now?

**Comment by juanfmx2** [comment]
it looks good thanks!
