### ISSUE TITLE
Add component information to binding_site endpoint

### ISSUE THREAD

**Issue by agaulton** [chembl/chembl_webservices_2#148]
Currently the binding_site endpoint returns domain information (where there is any) but does not include the component_id, which means there is no way to get back to the target_component that this refers to. If we could add the component_id, this would allow to retrieve the information from the target_component endpoint - or ideally, include selected target_component information (e.g. accession, description) in the binding_site endpoint. Open Targets may want to use this...

**Comment by mnowotka** [comment]
Component_id is now added: https://www.ebi.ac.uk/chembl/api/data/binding_site.json. @agaulton please let me know if this is what you wanted.

**Comment by agaulton** [comment]
Yes thanks
