### ISSUE TITLE
Add enzyme_chembl_id to Metabolism endpoint

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#149]
Here https://www.ebi.ac.uk/chembl/api/data/metabolism.json, there is a enzyme_name, but not enzyme_chembl_id. Enzyme is a target as far as I understand. It is required for https://github.com/chembl/GLaDOS/issues/298

**Comment by agaulton** [comment]
Yep, it's a target - use enzyme_tid to link

**Comment by mnowotka** [comment]
OK, I'll ad that. Fingers crossed for having a new release of API fixing all hanging requests this Monday!

**Comment by mnowotka** [comment]
SO it looks like this field is already there it's called target_chembl_id but often it's empty.
https://www.ebi.ac.uk/chembl/api/data/metabolism.json?target_chembl_id__isnull=false

**Comment by nclopezo** [comment]
I will use the target_chembl_id as the enzyme_chembl_id, thanks!
