### ISSUE TITLE
Add substrate_name and metabolite_name to Metabolism Endpoint 

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#150]
This is the query used in the current interface to get the metabolism data:

https://github.com/chembl/chembl_interface/blob/393cc16a11f17eb156673e9ab1ad734abdce608c/system/application/models/chembl.php#L2628

If I am correct (@agaulton) the metabolism table should have ```substrate_record_id``` and ```metabolite_record_id``` which should join to compound_records:

https://github.com/chembl/chembl_interface/blob/393cc16a11f17eb156673e9ab1ad734abdce608c/system/application/models/chembl.php#L2652
```SQL
where
...
 and m2.substrate_record_id = r2.record_id
 and m2.metabolite_record_id = r3.record_id
...
```

The substrate name should be the ```compound_key``` of to the compound record with the corresponding ```record_id```. And the same goes for the metabolite name.

**Comment by nclopezo** [comment]
This is required to finish https://github.com/chembl/GLaDOS/issues/298

**Comment by mnowotka** [comment]
Both requested fields are added now, see: https://www.ebi.ac.uk/chembl/api/data/metabolism.json
