### ISSUE TITLE
some queries to api are timeouted

### ISSUE THREAD

**Issue by piotr-gawron** [chembl/chembl_webservices_2#153]
I just noticed that some queries started to be time outed. Here is an example:
https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL1862

To be more specific. The error is about proxy error, but it happens after long time of waiting:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /chembl/api/data/target/CHEMBL1862.

Reason: Error reading from remote server
```

**Comment by mnowotka** [comment]
Thanks for reporting this, I can confirm that this problem exists and it looks that it only affects single targets. If you know about any other URLs (not single targets), please let me know. I will inform you when this issue is resolved.

**Comment by mnowotka** [comment]
OK, it should be better now but I'm still investigating the cause.

**Comment by piotr-gawron** [comment]
Great,

Thanks a lot for fast answer.

**Comment by mnowotka** [comment]
There was a storage issue which affected servers, it's fixed now but don't hesistate to create another ticket if there are more problems with the API.
