### ISSUE TITLE
Withdrawn Class

### ISSUE THREAD

**Issue by apbento** [chembl/chembl_webservices_2#156]
We have added a new field to the molecule_dictionary: withdrawn_class.

Could you please add that to the molecule endpoint of the web services.
We are already showing the withdrawn_flag, withdrawn_year, withdrawn_country, withdrawn_reason.
See for example: https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL127516

Thanks!

**Comment by agaulton** [comment]
Should also be added to Drugs endpoint. But looks like that may appear by default if we add this field to the MoleculeDictionary and MoleculeBrowseDrugs models?

**Comment by juanfmx2** [comment]
This has just been deployed in the web services:
https://www.ebi.ac.uk/chembl/api/data/molecule.json?withdrawn_class__isnull=false
