### ISSUE TITLE
molecule hierarchy not present within molecule API

### ISSUE THREAD

**Issue by FionaEBI** [chembl/chembl_webservices_2#160]
Hi Juan, 
For the TransQST platform, I notice that for two compounds there is no molecule hierarchy present within the 'molecule' web services API. 
These are: 'CHEMBL2110557'& 'CHEMBL1201289' for 'RUBIDIUM CHLORIDE' & 'CLINDAMYCIN PALMITATE'.
As far as I can tell from directly querying the chembl database in sql then both these molecules have a parent_chemblid and molecule_chemblid present - so it doesn't appear to be a curation issue. 
See the screenshots below:
![screen shot 2018-06-26 at 14 35 56](https://user-images.githubusercontent.com/32895834/41915747-5f5b13b2-794e-11e8-8808-10af59890a54.png)
![screen shot 2018-06-26 at 14 36 11](https://user-images.githubusercontent.com/32895834/41915750-5f81b2b0-794e-11e8-89eb-89e3af6b794a.png)

And the sql query direct on the database: 
![screen shot 2018-06-26 at 14 38 40](https://user-images.githubusercontent.com/32895834/41915894-b5653f4e-794e-11e8-8554-3e8d9c661c78.png)
![screen shot 2018-06-26 at 14 38 47](https://user-images.githubusercontent.com/32895834/41915895-b59a1fe8-794e-11e8-9b1f-9f32dd79b44d.png)

Thanks for your help!
Fiona

**Comment by FionaEBI** [comment]
Thinking about this further, I realise that this issue is to do with the compound being a virtual parent compound ie one that has no bioactivity data associated with it (the bioactivity data is associated with the salt, not the parent). I previously had a email conversation with Anna @agaulton about this, and she said that a parent compound is only present in the molecule hierarchy if it has associated bioactivity data (which is not true for virtual parent compounds). 

However, this means that it looks odd for a few compounds within the TransQST platform that have no parent_chembl_id - see screenshot. Perhaps this needs further thought?
![screen shot 2018-06-26 at 15 03 49](https://user-images.githubusercontent.com/32895834/41917404-2e13951e-7952-11e8-84c9-65228d20b6ce.png)

**Comment by juanfmx2** [comment]
closing in favor of chembl/chembl_data#72
