### ISSUE TITLE
minor typo in descriptions

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_webservices_2#36]
should be base64?
in https://www.ebi.ac.uk/chembl/api/utils/docs
image2ctab and image2smiles

![image](https://cloud.githubusercontent.com/assets/3305715/6105395/8336eb66-b04e-11e4-93b7-7eaaff759d3d.png)

**Comment by mnowotka** [comment]
This issue is about Beaker not web services. I've corrected it in the source code, unfortunately we will have to wait a bit for the release. But since the code was corrected, the typo was minor and concerns Beaker I'm closing this issue now.
