### ISSUE TITLE
Allow order_by on similarity field

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_webservices_2#38]
Currently not possible to order_by on similarity field:

https://www.ebi.ac.uk/chembl/api/data/similarity/CN1C%28=O%29C=C%28c2cccc%28Cl%29c2%29c3cc%28ccc13%29%5BC@@%5D%28N%29%28c4ccc%28Cl%29cc4%29c5cncn5C/80?order_by=similarity

Can this be added?

**Comment by mnowotka** [comment]
Very tricky as 'similarity' is kind of an artificial field. I will try to think of some solution though.

**Comment by mnowotka** [comment]
OK, there is a hope :)
https://stackoverflow.com/questions/1652577/django-ordering-queryset-by-a-calculated-field

**Comment by mnowotka** [comment]
This is now fixed but let me add that you would probably want to sort by `-similarity`.
