### ISSUE TITLE
SMILES flex matching

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_webservices_2#41]
Old chembl web services use flex (I think), to match on smiles:

https://www.ebi.ac.uk/chemblws/compounds/substructure/CN%28CCCN%29c1cccc2ccccc12

Different behaviour in new web services:

https://www.ebi.ac.uk/chembl/api/data/substructure/CN%28CCCN%29c1cccc2ccccc12

Possibly consider adding a flex search option:

https://www.ebi.ac.uk/chembl/api/data/substructure/canonical_smilles__flex=CN%28CCCN%29c1cccc2ccccc12

**Comment by mnowotka** [comment]
This is now implemented and the example link is:

https://www.ebi.ac.uk/chembl/api/data/molecule?molecule_structures__canonical_smiles__flexmatch=COc1ccc2[C@@H]3[C@H]%28COc2c1%29C%28C%29%28C%29OC4=C3C%28=O%29C%28=O%29C5=C4OC%28C%29%28C%29[C@H]6COc7cc%28OC%29ccc7[C@@H]56
