### ISSUE TITLE
Create chembl_id_lookup resource

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_webservices_2#49]
Example requesting URL:
```
<base_url>/api/data/chembl_id_lookup/CHEMBL25
```
Example response:
```
<response>
  <chembl_id_lookups>
    <chembl_id_lookup>
      <chembl_id>CHEMBL25</chembl_id>
      <entity_type>COMPOUND</entity_type>
      <entity_id>1280</entity_id>
      <status>ACTIVE</status>
      <resource_url>/api/data/molecule/CHEMBL25</resource_url>
    </chembl_id_lookup>
  </chembl_id_lookups>
</response>
```

Entity types currently in chembl_id_lookup table:

DOCUMENT
TARGET
COMPOUND
ASSAY
CELL

**Comment by mnowotka** [comment]
Done, examples:

https://www.ebi.ac.uk/chembl/api/data/chembl_id_lookup/CHEMBL1

https://www.ebi.ac.uk/chembl/api/data/chembl_id_lookup?entity_type=TARGET&status=ACTIVE
