### ISSUE TITLE
Review live docs descriptions

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_webservices_2#51]
If there are any hidden parameters these should be included. For example the image resource  has a number special arguments. If this ends up being tricky, we could add a link to an anchor in this page: https://www.ebi.ac.uk/chembl/ws

We could also consider adding the link to the schema, e.g. https://www.ebi.ac.uk/chembl/api/data/molecule/schema.json. Not immediately readable, but would be useful for users familiar with the services.

**Comment by mnowotka** [comment]
OK, apart from images, is there any other resource, that currently have undocumented parameters?

**Comment by mark-davies** [comment]
The flex search on molecules

**Comment by mnowotka** [comment]
Right, thanks.

**Comment by mnowotka** [comment]
Fixed.
