### ISSUE TITLE
Provide new WS use case

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_webservices_2#52]
Data mining/machine learning example: 
Extract all 'good' activities for all 'good' targets and 'good' molecules.

**Comment by mnowotka** [comment]
https://www.ebi.ac.uk/chembl/api/data/activity?molecule__is_good=True&target__is_good=True

**Comment by madgpap** [comment]
hahaha
see also:
https://www.ebi.ac.uk/chembl/api/data/activity?solve_my_problem=True

**Comment by madgpap** [comment]
This is what I had in mind
```
cp.mw_freebase BETWEEN 150 AND 1000
AND
cp.aromatic_rings <= 7
and
cp.rtb <= 20
AND
cp.heavy_atoms BETWEEN 7 AND 42
AND
cp.alogp BETWEEN -4 AND 10
AND
cp.num_alerts <= 4
and
ac.STANDARD_UNITS = 'nM'
AND
ac.STANDARD_TYPE in ('EC50', 'IC50', 'Ki', 'Kd', 'XC50', 'AC50', 'Potency')
and
ac.standard_value <= 10000
and
ac.data_validity_comment is null
and
ac.standard_relation in ('=','<')
and
ac.potential_duplicate is null
and
ass.confidence_score >= 8
and
td.target_type = 'SINGLE PROTEIN'
```

**Comment by mnowotka** [comment]
Leaving as an exercise for the reader.

**Comment by mnowotka** [comment]
Since we've already submitted the manuscript and this is not related to web services core functionality, I'm closing this issue.
