### ISSUE TITLE
Review biotherapeutic responses

### ISSUE THREAD

**Issue by mark-davies** [chembl/chembl_webservices_2#53]
A review of the biotherapeutic/biocomponent tables suggests an update to the web services is probably required. A proposed change to the molecule endpoint would be:
```
<molecule>
   ....
   ....
   <biotherapeutic>
       <molecule_chembl_id></molecule_chembl_id>   <- This would be the same as the molecule chembl_id
       <description></description>
       <helm></helm>
       <biocomponents>
           <biocomponent>
           ....
           </biocomponent>
           <biocomponent>
           ....
           </biocomponent>
       </biocomponents>
   </biotherapeutic>
</molecule>
```
Basically biocomponents is moved into the biotherapeutic tag and the biotherapeutic description is also added.

Also the biocomponent endpoint should probably be replaced with biotherapeutic endpoint and response would be (same as above):
```
<biotherapeutics>
   <biotherapeutic>
       <molecule_chembl_id></molecule_chembl_id> 
       <description></description>
       <helm></helm>
       <biocomponents>
           <biocomponent>
           ....
           </biocomponent>
           <biocomponent>
           ....
           </biocomponent>
       </biocomponents>
   </biotherapeutic>
   ....
   ....
</biotherapeutics>
```

**Comment by mark-davies** [comment]
Example of biotherapeutic without biocomponent:  https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL7122

Example of biotherapeutic with biocomponent:  https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL1201558

**Comment by mnowotka** [comment]
Done, some examples:

https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL1201558
https://www.ebi.ac.uk/chembl/api/data/biotherapeutic
