### ISSUE TITLE
Source endpoint contains extra entry

### ISSUE THREAD

**Issue by madgpap** [chembl/chembl_webservices_2#65]
https://www.ebi.ac.uk/chembl/api/data/source
![image](https://cloud.githubusercontent.com/assets/3305715/7421049/70fefb36-ef79-11e4-8fe0-5bf5bb9cddf5.png)

Fix: Remove from app_schema

**Comment by agaulton** [comment]
I guess I overlooked this in cleaning the app schema. Will try to make sure the data cleanup is identical to the export schema in future. Can remove it from the db though.

**Comment by mnowotka** [comment]
Since the problem with DB is now resolved but cache still contains old data I'm reassigning this.

**Comment by mnowotka** [comment]
Fixed.
