### ISSUE TITLE
expose compound synosyms

### ISSUE THREAD

**Issue by mnowotka** [chembl/chembl_webservices_2#73]
Currently there is no possibility to search compounds via synonyms. Issue https://github.com/chembl/chembl_webservices_2/issues/4 aims to fix this in a very elegant way, but maybe there is something that can be done without SOLR, just using current stack. There are two ways:

1. From molecule side: URL like: `https://www.ebi.ac.uk/chembl/api/data/molecule?molecule_synonyms__synonyms=viagra` but this one is tricky.

2. Expose `molecule_synonyms` as a resource on its own so we would have something like:

`https://www.ebi.ac.uk/chembl/api/data/molecule_synonyms?synonyms=viagra`

and them maybe try to hook it up into `molecule` resource just like `image` is hooked into `molecule`

**Comment by agaulton** [comment]
Yes, this would be v useful!

**Comment by madgpap** [comment]
Another use-case:
```
https://www.ebi.ac.uk/chembl/api/data/molecule?molecule_synonyms__synonym__startswith=MMV&limit=1000
```

**Comment by mnowotka** [comment]
Fixed but the correct link is now:
https://www.ebi.ac.uk/chembl/api/data/molecule/search.json?q=viagra
