### ISSUE TITLE
Return 404 when compound can't be drawn

### ISSUE THREAD

**Issue by mnowotka** [chembl/chembl_webservices_2#75]
Example of problematic molecule is here:

https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL450200

The image should be here:

https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL450200

But for some reason it returns 500.

Interestingly indigo can handle this: https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL450200?engine=indigo

So it means this is a problem with rdkit. So what I think should be done in that case is - if rdkit fails to load molecule use indigo instead and notify sentry, if they both fail, provide message from one of them which should explain the source of the problem.

**Comment by madgpap** [comment]
pentavalent Nitrogen, baby.

**Comment by mnowotka** [comment]
Fixed using:
         
        mol = Chem.MolFromMolBlock(str(molstring), sanitize=False)
        mol.UpdatePropertyCache(strict=False)
