### ISSUE TITLE
Pull back a count of activities when searching on an assay

### ISSUE THREAD

**Issue by ljbellis** [chembl/chembl_webservices_2#81]
Currently, it is not possible to get a count of activities when calling on a specific assay

e.g. https://www.ebi.ac.uk/chembl/api/data/assay?assay_chembl_id=CHEMBL1022848

A user has requested this because they want to run a search on, say, an assay with 'Kinase' in the description and they judge how useful an assay might be by the number of activities linked to it.

I have replied to them and explained that it's calling on two tables and it might not be able to be implemented but I wanted to add it to the list for possible consideration. # #

**Comment by mnowotka** [comment]
This is already in our plans: https://github.com/chembl/chembl_webservices_2/issues/54.
