### ISSUE TITLE
When look at Mechanism of Action data for a molecule, can it also show references?

### ISSUE THREAD

**Issue by ljbellis** [chembl/chembl_webservices_2#93]
Currently, on the interface Mechanism of Action has references linked to the data.

e.g. https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2068724

When pulling back the same information via the web services, reference data is not displayed.

https://www.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id=CHEMBL2068724 

Is this something which can be added?

**Comment by mnowotka** [comment]
Yes, in fact I was discussing this today with @nclopezo as this will be necessary for the new interface.

**Comment by mnowotka** [comment]
Again, tagging @nclopezo to let you know that this is deployed to dev server:
https://wwwdev.ebi.ac.uk/chembl/api/data/mechanism?molecule_chembl_id=CHEMBL2068724

**Comment by mnowotka** [comment]
Fixed.
