### ISSUE TITLE
Protein target classification missing for Targets

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#95]
When I get the information about a target it seems that it is missing the "Protein Target Classification".

For example, for [CHEMBL1697668](https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL1697668) the [web service response](https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL1697668.json)  doesn't contain this information. Could it be included?

In the web interface it says 'Not applicable' when necessary: [CHEMBL2367428](https://wwwdev.ebi.ac.uk/chembl/target/inspect/CHEMBL2367428)

**Comment by mnowotka** [comment]
So this is how you should get the "Protein Target Classification" info:

1. Go to target: https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL1697668.json and extract all component ids. In practice the number should almost always be 0 or 1. In our case, we have a single component with the `component_id` = 4879.

2. For each component id, visit the `target_component` endpoint, in our case:
https://www.ebi.ac.uk/chembl/api/data/target_component/4879.json and extract the `protein_classification_id` (should always be a single id, but for some reason we have it in an array, I will change that some day, but now it doesn't matter). In our case this is `protein_classification_id` =  709

3. Once you have the `protein_classification_id` go to the `protein_class` endpoint: https://www.ebi.ac.uk/chembl/api/data/protein_class/709.json

And this is the data you were looking for.

**Comment by agaulton** [comment]
It is possible to have multiple protein classifications for a component, that's why we had an array e.g., for target CHEMBL2933, component_id = 1263 is both a 'Sodium potassium ATPase' and a 'Hydrolase'

**Comment by mnowotka** [comment]
OK, good to know :)
Anyway, in practice the number of (`component_id`s x `protein_classification_id`s) should be small in most cases. And I guess you need to fetch component info for other stuff in the target report card as well.

**Comment by nclopezo** [comment]
For the record, this has been implemented: https://www.ebi.ac.uk/panda/jira/browse/CHEMBLWEB-10
