### ISSUE TITLE
Targets: add more properties for the Target Components list

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#96]
For the target components listed for a target for example [CHEMBL2364672](https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL2364672.json):

Could the properties "component_description" and "relationship" be added? 

Like this:

```
{
  organism: "Bacteria",
  pref_name: "Bacterial DNA-directed RNA polymerase",
  species_group_flag: true,
  target_chembl_id: "CHEMBL2364672",
  target_components: [
    {
    accession: "P0A7Z4",
    component_id: 7857,
    component_type: "PROTEIN",
    component_description: "Fatty-acid amide hydrolase 1",  <---
    relationship: "GROUP MEMBER", <---
    target_component_synonyms: [
      {
        component_synonym: "2.7.7.6",
        syn_type: "EC_NUMBER"
      },
      ...
```

**Comment by mnowotka** [comment]
Fixed in code, not yet deployed.

**Comment by mnowotka** [comment]
Deployed to dev server: https://wwwdev.ebi.ac.uk/chembl/api/data/target/CHEMBL2364672.json

**Comment by nclopezo** [comment]
This has been implemented: http://glados-ebitest.rhcloud.com/target_report_card/CHEMBL2364672/
