### ISSUE TITLE
Targets: add a list of Target Relations

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#97]
For the information obtained for a target, for example [CHEMBL2364672](https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL2364672.json):
Could a list of the target relations be added?

Like this:
```
{
  organism: "Bacteria",
  pref_name: "Bacterial DNA-directed RNA polymerase",
  species_group_flag: true,
  target_chembl_id: "CHEMBL2364672",
  target_components: [ ... ],
  target_relations: [
     { 
        chembl_id: "CHEMBL1852",
        pref_name:"DNA-directed RNA polymerase beta chain",
        target_type:"SINGLE PROTEIN"
     },
      ....

```

**Comment by mnowotka** [comment]
I added a separate resource called `target_relation`. To be released.

**Comment by mnowotka** [comment]
Deployed to dev server: https://wwwdev.ebi.ac.uk/chembl/api/data/target_relation.json

**Comment by nclopezo** [comment]
This has been implemented: https://www.ebi.ac.uk/panda/jira/browse/CHEMBLWEB-10

**Comment by mnowotka** [comment]
URL, pls?

**Comment by nclopezo** [comment]
You can see it here: http://glados-ebitest.rhcloud.com/target_report_card/CHEMBL3559691/#TargetRelations
