### ISSUE TITLE
Tissue: Add the resource to the web services. 

### ISSUE THREAD

**Issue by nclopezo** [chembl/chembl_webservices_2#99]
Could a new resource be added for tissues? For now the response for a particular tissue could be something like this:

```
{
  chembl_id: "CHEMBL3559721",
  name:  "blood plasma",
  uberon_id: "UBERON:0001969",
  efo_id: "EFO:0008529"
}
```

**Comment by mnowotka** [comment]
Yes, tissue is added and will be available since ChEMBL 22.
